Map<String, dynamic> refactorUserInformation({required Map<String, dynamic> res}) {
  Map<String, dynamic> accountInfo = res['account_info'] ?? {};
  Map<String, dynamic> employeeInfo = res['employee_info'] ?? {};

  // debugLog(accountInfo);
  // debugLog(employeeInfo);
  Map<String, dynamic> user = {
    'phone': accountInfo['phone'],
    'gender': accountInfo['gender'],
    'is_verify_phone': accountInfo['is_verify_phone'],
    'avatar': accountInfo['avatar'],
    'bank_info': accountInfo['bank_info'],
    'first_name': accountInfo['first_name'],
    'email': accountInfo['email'],
    'last_name': accountInfo['last_name'],
    'current_address': accountInfo['current_address'],
    'extra_info': accountInfo['extra_info'],
    'dob': accountInfo['dob'],
    'username': accountInfo['username'],
    'identity_card_info': accountInfo['identity_card_info'],
    'identity_card_front': accountInfo['identity_card_front'],
    'identity_card_back': accountInfo['identity_card_back'],
    'is_verify_identity_card': accountInfo['is_verify_identity_card'],
    'account_status': accountInfo['status'],
    'face_image': accountInfo['face_image'],
    "bio": accountInfo['bio'],
    "other_phone": accountInfo['other_phone'],
    "tax_info": accountInfo['tax_info'],
    "middle_name": accountInfo['middle_name'],
    'status': employeeInfo['status'],
    'role_id': employeeInfo['role_id'],
    'type_id': employeeInfo['type_id'],
    'is_accept_rule': employeeInfo['is_accept_rule'],
    'parttime_salary_by_day': employeeInfo['parttime_salary_by_day'],
    'dept_id': employeeInfo['dept_id'],
    'id': employeeInfo['id'],
    'store_id': employeeInfo['store_id'],
    "ref_email_receive_experience": employeeInfo['ref_email_receive_experience'],
    "code": employeeInfo['code'],
    "salary": employeeInfo['salary'],
    "is_join_insurance": employeeInfo['is_join_insurance'],
    "join_date": employeeInfo['join_date'],
    "level_id": employeeInfo['level_id'],
    "probation_id": employeeInfo['probation_id'],
    "salary_insurance": employeeInfo['salary_insurance'],
    "join_date_official": employeeInfo['join_date_official'],
    "store_working_id": employeeInfo['store_working_id'],
    "fulltime_number_hour_per_workday": employeeInfo['fulltime_number_hour_per_workday'],
    "is_join_tax": employeeInfo['is_join_tax'],
    "salary_kpi": employeeInfo['salary_kpi'],
    "role_extra": employeeInfo['role_extra'],
    "company_id": employeeInfo['company_id'],
    "language": accountInfo['language'],
    "is_manager_employee_no_smartphone": employeeInfo['is_manager_employee_no_smartphone'],
    "role_data": employeeInfo['role_data'],
    "role_uid": employeeInfo['role_uid'],
    "is_calculate_salary": employeeInfo['is_calculate_salary'],
    "is_check_in_out": employeeInfo['is_check_in_out'],
    "id_card": accountInfo['id_card'],
  };
  return user;
}
